apiVersion: v1
kind: Service
metadata:
  name: echo
  annotations:
    ingress-rules/name: echo
    ingress-rules/host: test.ingress.rules
spec:
  type: NodePort
  selector:
    app: echo
  ports:
  - name: http
    port: 80
    targetPort: 8080
