apiVersion: v1
kind: Service
metadata:
  name: echo
  annotations:
    ingress-rules/name: ingress-rules
    ingress-rules/host: echo-1.deploy.footway.com
spec:
  type: NodePort
  selector:
    app: echo
  ports:
  - name: http
    port: 80
    targetPort: 8080
